services:

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
     image: postgres:13-alpine
     restart: always
     ports:
      - '5432:5432'
     volumes:
        - .data:/var/lib/postgresql/data
     environment:
        POSTGRES_RANDOM_ROOT_PASSWORD: yes
        POSTGRES_DB: app
        POSTGRES_USER: app
        POSTGRES_PASSWORD: pass

